apiVersion: v1
kind: Secret
metadata:
  name: products-mongo
type: Opaque
data:
  username: cm9vdA==
  password: bXN2Yw==
  mongo_connection: bW9uZ29kYjovL3Jvb3Q6bXN2Y0Btb25nb2RiOjI3MDE3L2FkbWlu
---
apiVersion: v1
kind: Secret
metadata:
  name: users-postgres
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=