version: '3.9

services:
  user_app:
  	container_name: user_app
  	image: finconecta-user-app:0.0.1
  	build: .
	  ports:
	   -8080:8080
	  environment:
	  - DATABASE_URL=jdbc:postgresql://postgres_db:15432/postgres
	  - DATABASE_USERNAME= postgres
	  - DATABASE_PASSWORD= msvc
	  depends_on
	  - user_db
  user_db